### ISSUE TITLE
1.5.6 to 1.6.9(docker install)

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-memcached#1]
1.5.6 to 1.6.9

**Comment by qiaofeng1227** [comment]
Yum: the latest version is 1.4.15, and there no 1.6.9 in the repo SCL and CentOS7 base
APT:  the latest version is 1.5.6 at Ubuntu18.04 base

**Comment by qiaofeng1227** [comment]
change to docker intall
